### PR TITLE
updated readme, removed redundant readme, changed mkldiscover message

### PR DESCRIPTION
**Pull request by charnley**

### CODE REVIEW

**Comment by andersx** [comment]
Can you provide a link that shows readme.rst is properly rendered on github?

**Comment by charnley** [comment]
https://github.com/charnley/rmsd

**Comment by andersx** [comment]
That link is to another project

**Comment by charnley** [comment]
https://github.com/qmlcode/qml/blob/master/README.rst

**Comment by andersx** [comment]
also this file
https://github.com/charnley/qml/blob/e2710c5c835c9a468fcc9a0d1f0aeabb13a16f1a/setup.py#L137

**Pull request merged**
