### PR TITLE
macOS on Travis-CI

### PR DESCRIPTION
**Pull request by RMeli**
Added `macOS` on Travis-CI, addressing #57.

Linux build passes successfully, macOS build fails because of #119.

### CODE REVIEW

**Comment by andersx** [comment]
Once again, thank you for the valuable macOS Travis PRl We had a pull request from Casper Steinmann which should have fixed the seg/fault bug on macOS. 

I revieved this PR, but this time Tensorflow seems to have changed it's API. I'll see if I can get this fixed now.

**Comment by RMeli** [comment]
Good tho hear that the issue should be solved, thanks! 

I think `pip` is now trying to install TF 2 and should probably be pinned to TF 1.x. I can try to fix this later today or tomorrow.

**Comment by andersx** [comment]
Yeah, I think you are right! I don't know what it will require to migrate the code, I think simply requiring tensorflow==1.x be enough for now. 

I don't know if the following is a more long-term solution for the TF code:
````
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
````
Pinging @larsbratholm

**Comment by andersx** [comment]
I was trying to get a mac mini for some more internal testing, before I would merge in this change. However, looks like I am not getting one any time soon. I'll look into this again now!

**Comment by RMeli** [comment]
Closing as stale. Feel free to re-open if needed.

**Pull request closed without merging**
